adapter.sqs.statuschange.queue-url:${SPRING_SQS_URL_STATUSCHANGE}
adapter.sqs.statuschange.region:${SPRING_SQS_REGION_STATUSCHANGE}

adapter.sqs.calculatedebtcapacity.queue-url:${SPRING_SQS_URL_CALCULATEDEBTCAPACITY}
adapter.sqs.calculatedebtcapacity.region:${SPRING_SQS_REGION_CALCULATEDEBTCAPACITY}
